league = true
daily = true

[ui]
    hotkeys = { ocr = '`' }

[ocr]
    bounds = { left=335, top=210, right=916, bottom=455 }  # for 1920x1080 screen resolution (fullscreen windowed)
    # bounds = { left=450, top=277, right=1225, bottom=616 }  # for 2560x1440
